stateDiagram-v2
    [*] --> Pending
    Sunsetting --> Pending : Rollback
    Maintenance --> Pending : MaintenanceSuccess
    Pending --> Active : Activate
    Sunsetting --> Terminated : Terminate
    Maintenance --> Terminated : Terminate
    Active --> Sunsetting : Deactivate
    Sunsetting --> Maintenance : Maintain
