stateDiagram-v2
    [*] --> Pending
    Maintenance --> Terminated : Terminate
    Maintenance --> Pending : MaintenanceSuccess
    Sunsetting --> Maintenance : Maintain
    Active --> Sunsetting : Deactivate
    Sunsetting --> Terminated : Terminate
    Sunsetting --> Pending : Rollback
    Pending --> Active : Activate
