stateDiagram-v2
    [*] --> Created
    Shipped --> Cancelled : Cancel
    Created --> Cancelled : Cancel
    Created --> Paid : Pay
    Paid --> Cancelled : Refund
    Paid --> Shipped : Ship
    Shipped --> Delivered : Deliver
