stateDiagram-v2
    [*] --> Pending
    Sunsetting --> Pending : Rollback
    Sunsetting --> Maintenance : Maintain
    Active --> Sunsetting : Deactivate
    Maintenance --> Terminated : Terminate
    Pending --> Active : Activate
    Maintenance --> Pending : MaintenanceSuccess
    Sunsetting --> Terminated : Terminate
