stateDiagram-v2
    [*] --> Pending
    Pending --> Active : Activate
    Sunsetting --> Maintenance : Maintain
    Sunsetting --> Terminated : Terminate
    Active --> Sunsetting : Deactivate
    Maintenance --> Terminated : Terminate
    Maintenance --> Pending : MaintenanceSuccess
    Sunsetting --> Pending : Rollback
    Maintenance --> Maintenance : EditDesc
    Active --> Active : EditDesc
    Terminated --> Terminated : EditDesc
    Sunsetting --> Sunsetting : EditDesc
    Pending --> Pending : EditDesc
